characters/characters/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main_app.urls")),
]

characters/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name = "home"),
    path ("about/", views.about, name = "about"),
    path("characters/", views.characters_index, name="index"),
    path('characters/<int:character_id>/', views.characters_detail, name='detail'),
    path('characters/create/', views.CharacterCreate.as_view(), name='characters_create'),
    path('characters/<int:pk>/update/', views.CharacterUpdate.as_view(), name='characters_update'),
    path('characters/<int:pk>/delete/', views.CharacterDelete.as_view(), name='characters_delete'),
    path("characters/<int:character_id>/add_action", views.add_action, name = "add_action"),
]

characters/main_app/models.py
from statistics import mode
from django.db import models
from django.urls import reverse


ACTION_TYPE = (
    ("G", "Good"),
    ("B", "Bad"),
    ("N", "Necessary/Neutral"),
    ("S", "Subjective") 
)
# Create your models here.
class Character(models.Model):
    name = models.CharField(max_length=100)
    media_name = models.CharField(max_length=100)
    movie_format = models.BooleanField()
    year_created = models.IntegerField()
    description = models.TextField(max_length=500)
    role = models.CharField(max_length=100)
    goal = models.CharField(max_length=100)
    obstacle = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("detail", kwargs = {"character_id": self.id})

class Action(models.Model):
    action = models.CharField(max_length=100)
    reason = models.CharField(max_length=100)
    action_type = models.CharField(
        "Type of action",
        max_length=1,
        choices=ACTION_TYPE,
        default=ACTION_TYPE[2][0]
    )
    character = models.ForeignKey(Character, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.action} was {self.get_action_type_display()}"

characters/main_app/forms.py
from django.forms import ModelForm
from .models import Action

class ActionForm(ModelForm):
    class Meta:
        model = Action
        fields = ["action", "reason", "action_type"]

characters/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView 
from .models import Character
from .forms import ActionForm 

# Create your views here.

class CharacterCreate(CreateView):
  model = Character
  fields = "__all__"


class CharacterUpdate(UpdateView):
  model = Character
  fields = ["media_name", "year_created", "description", "role", "goal", "obstacle"]


class CharacterDelete(DeleteView):
  model = Character
  success_url = '/characters/'


def home(request):
  return render(request, "home.html")

def about(request):
    return render(request, "about.html")

def characters_index(request):
  characters = Character.objects.all()
  return render(request, "characters/index.html", { "characters": characters })

def characters_detail(request, character_id):
  character = Character.objects.get(id=character_id)
  action_form = ActionForm()
  return render(request, "characters/detail.html", { "character": character, "action_form": action_form } )

def add_action (request, character_id):
  form = ActionForm(request.POST)
  if form.is_valid():
    new_action = form.save(commit=False)
    new_action.character_id = character_id
    new_action.save()
  return redirect('detail', character_id=character_id)

characters/main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1>About the Character Collector</h1>
<hr />
<p>Hire the Character Collector!</p>
{% endblock %}

characters/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Character Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo"
                >&nbsp;&nbsp;Character Collector</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'characters_create' %}">Add Character</a></li>
            <li><a href="{% url 'index' %}">View Characters</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2022 Character Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

characters/main_app/templates/characters/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Character Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><strong>{{ character.name }}</strong></span>
        {% if character.movie_format %}
        <p>Movie character</p>
        {% else %}
        <p>TV character</p>
        {% endif %}
        <p><b>{{ character.media_name }}</b></p>
        <p><b>Year Created: </b>{{ character.year_created }}</p>

        <br />
        <p><b>Description: </b>{{ character.description }}</p>
        <p><b>Role: </b>{{ character.role }}</p>
        <p><b>Main goal: </b>{{ character.goal }}</p>
        <p><b>Obstacle: </b>{{ character.obstacle }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'characters_update' character.id %}">Edit</a>
        <a href="{% url 'characters_delete' character.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_action' character.id %}" method="post">
      {% csrf_token %} {{ action_form.as_p }}
      <input type="submit" class="btn" value="Add Action" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Action</th>
          <th>Reason</th>
          <th>Type of Action</th>
        </tr>
      </thead>
      <tbody>
        {% for action in character.action_set.all %}
        <tr>
          <td>{{action.action}}</td>
          <td>{{action.reason}}</td>
          <td>{{action.get_action_type_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script>
  let selectEl = document.getElementById("id_action_type");
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

characters/main_app/templates/characters/index.html
{% extends 'base.html' %} {% block content %}

<h1>Character List</h1>

{% for character in characters %}
<a href="{% url 'detail' character.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ character.name }}</span>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

characters/main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Home</h1>

{% endblock %}

characters/main_app/templates/main_app/character_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Character</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' character.id %}">Cancel</a>
</form>
{% endblock %}

characters/main_app/templates/main_app/character_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Character</h1>

{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
<script>
  let checkboxEl = document.getElementById("id_movie_format");
  M.FormSelect.init(checkboxEl);
</script>
{% endblock %}